# -*- coding: utf-8 -*-
"""capston.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I6lGZumM7QvuREIvjIvk7PMmAUPRHT16

[link text](https://)# Livestock Breed Classification using Deep Learning

This notebook demonstrates how to build, train, and evaluate a deep learning model for classifying livestock breeds using the Indian Cattle Image Dataset. The model utilizes transfer learning with MobileNetV2 for high accuracy.

---

## 1. Setup and Library Installation

First, we'll install necessary libraries and import all modules required for the project.
"""

# Install necessary libraries
!pip install tensorflow kagglehub opencv-python-headless matplotlib

# Import required modules
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras import layers, models
from tensorflow.keras.callbacks import EarlyStopping
import matplotlib.pyplot as plt
import kagglehub
import os
import shutil
import numpy as np
import cv2
from IPython.display import Image, display
from google.colab import files

"""## 2. Data Handling

We will download the specified dataset from Kaggle, extract it, and filter it to include only the selected breeds.
"""

import kagglehub
import os

# Download dataset using kagglehub
dataset_name = "atharvadarpude/indian-cattle-image-dataset"
path = kagglehub.dataset_download(dataset_name)
print(f"Dataset downloaded to: {path}")

# Print dataset structure to verify
print("\nDataset structure (first level):")
for root, dirs, file_names in os.walk(path):
    print(root)
    if dirs: # Only print directories, not files at the top level
        print(f"  Subdirectories: {dirs}")
    break

cattle_base_path = os.path.join(path, 'cattle')
if os.path.exists(cattle_base_path):
    print(f"\nContents of the 'cattle' directory: {os.listdir(cattle_base_path)[:10]}... (showing first 10)")
else:
    print(f"Warning: 'cattle' directory not found at {cattle_base_path}. Please check the dataset structure.")

# Select only 5 breeds for initial training
# Note: As observed in previous interactions, 'Holstein' and 'Jersey' might not be present in this dataset.
# If you encounter errors, you may need to adjust this list based on available breeds.
selected_classes = ["Gir", "Holstein", "Jersey", "Sahiwal", "Red_Sindhi"]

base_dir = "/content/filtered_dataset"

# Clean up previous filtered dataset if it exists
if os.path.exists(base_dir):
    shutil.rmtree(base_dir)

# Create new base directory
os.makedirs(base_dir, exist_ok=True)

print(f"Filtering dataset for selected classes: {selected_classes}")

missing_classes = []
for cls in selected_classes:
    src_path = os.path.join(cattle_base_path, cls)
    dst_path = os.path.join(base_dir, cls)

    if os.path.exists(src_path):
        shutil.copytree(src_path, dst_path)
        print(f"Copied class: {cls}")
    else:
        missing_classes.append(cls)
        print(f"Warning: Source directory not found for class '{cls}' at {src_path}. Skipping this class.")

if missing_classes:
    print(f"\nThe following classes were not found in the dataset and were skipped: {missing_classes}")

# Update selected_classes to only include those actually copied
selected_classes = [cls for cls in selected_classes if cls not in missing_classes]
print(f"\nSuccessfully prepared dataset with classes: {selected_classes}")

"""*italicized text*## 3. Data Preprocessing

We'll use `ImageDataGenerator` for rescaling, validation split, and data augmentation to prepare the images for the model.
"""

img_size = (224, 224)
batch_size = 32

datagen = ImageDataGenerator(
    rescale=1./255,           # Rescale pixel values to [0, 1]
    validation_split=0.2,     # 20% of data for validation
    rotation_range=25,        # Randomly rotate images by up to 25 degrees
    zoom_range=0.2,           # Randomly zoom images by up to 20%
    horizontal_flip=True,     # Randomly flip images horizontally
    fill_mode='nearest'       # Fill in new pixels created by rotation or shift
)

train_data = datagen.flow_from_directory(
    base_dir,
    target_size=img_size,
    batch_size=batch_size,
    class_mode='categorical',
    subset='training',
    shuffle=True
)

val_data = datagen.flow_from_directory(
    base_dir,
    target_size=img_size,
    batch_size=batch_size,
    class_mode='categorical',
    subset='validation',
    shuffle=False # No need to shuffle validation data
)

"""## 4. Model Architecture (Transfer Learning with MobileNetV2)

We'll use a pre-trained MobileNetV2 model as a base and add custom layers for our classification task. Initially, the base model will be frozen.
"""

num_classes = len(selected_classes)

# Load pre-trained MobileNetV2 base model
base_model = MobileNetV2(
    weights='imagenet',       # Use weights pre-trained on ImageNet
    include_top=False,        # Exclude the top classification layer
    input_shape=(img_size[0], img_size[1], 3) # Specify input image shape
)

# Freeze the base model layers
base_model.trainable = False

# Build the custom classification head
model = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(), # Reduces spatial dimensions to 1x1
    layers.BatchNormalization(),     # Normalizes activations for stability
    layers.Dense(128, activation='relu'), # Fully connected layer with ReLU activation
    layers.Dropout(0.4),             # Dropout for regularization
    layers.Dense(num_classes, activation='softmax') # Output layer with softmax for multi-class classification
])

# Compile the model
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# Display model summary
model.summary()

"""## 5. Training the Model (Initial Phase)

We'll train the model for a few epochs with early stopping to prevent overfitting. The base model remains frozen during this phase.
"""

early_stop = EarlyStopping(patience=3, restore_best_weights=True, monitor='val_loss')

print("Starting initial model training...")
history = model.fit(
    train_data,
    validation_data=val_data,
    epochs=20, # Train for up to 20 epochs, early stopping will stop if no improvement
    callbacks=[early_stop]
)
print("Initial training complete.")

"""## 6. Visualization

Plot the training and validation accuracy and loss over epochs to evaluate model performance.
"""

plt.figure(figsize=(12, 5))

# Plot training & validation accuracy values
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Model accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'], loc='upper left')

# Plot training & validation loss values
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Model loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'], loc='upper left')

plt.tight_layout()
plt.show()

"""## 7. Model Saving

Save the trained model for future use and provide an option to download it.
"""

model_save_path = "/content/breed_model.h5"
model.save(model_save_path)
print(f"Model saved to {model_save_path}")

# Provide a download link
files.download(model_save_path)

"""## 8. Prediction Function

Define a `predict_image` function that takes an image path, preprocesses it, and returns the top breed predictions with confidence and a crossbreed ratio.
"""

from tensorflow.keras.models import load_model

# Reload the best model to ensure we use the restored weights
model = load_model(model_save_path)

# Create a list of class names in the order they were indexed by ImageDataGenerator
class_names = list(train_data.class_indices.keys())

def predict_image(img_path):
    img = cv2.imread(img_path) # Load image using OpenCV
    if img is None:
        raise FileNotFoundError(f"Image not found or cannot be loaded: {img_path}")

    img = cv2.resize(img, img_size) # Resize to target size
    img = img / 255.0                  # Normalize pixel values
    img = np.expand_dims(img, axis=0)  # Add batch dimension

    preds = model.predict(img)[0]      # Get predictions

    # Get top 2 prediction indices
    top_indices = preds.argsort()[-2:][::-1]

    primary_breed = class_names[top_indices[0]]
    secondary_breed = class_names[top_indices[1]]
    confidence = float(preds[top_indices[0]])

    # Return all predictions as a list for crossbreed ratio
    crossbreed_ratio = preds.tolist()

    return {
        "primary_breed": primary_breed,
        "secondary_breed": secondary_breed,
        "confidence": confidence,
        "crossbreed_ratio": crossbreed_ratio
    }

print("Prediction function 'predict_image' defined.")

"""### Test the Prediction Function

Let's test our `predict_image` function with a sample image from the dataset.
"""

# Get a sample image path for testing the prediction function
# Ensure 'Gir' is a class that was successfully copied
if selected_classes:
    sample_class = selected_classes[0]
    sample_image_dir = os.path.join(base_dir, sample_class)

    if os.path.exists(sample_image_dir) and os.listdir(sample_image_dir):
        sample_image_name = os.listdir(sample_image_dir)[0] # Take the first image
        sample_image_path = os.path.join(sample_image_dir, sample_image_name)
        print(f"Using sample image for prediction: {sample_image_path}")

        # Make a prediction
        prediction_results = predict_image(sample_image_path)
        print("\nPrediction Results:")
        print(prediction_results)
    else:
        print(f"Could not find sample images in {sample_image_dir}. Please ensure the directory exists and contains images.")
else:
    print("No classes were successfully processed to create a filtered dataset. Cannot run prediction test.")

"""## 9. Advanced Feature: Fine-tuning the Model

To potentially improve accuracy, we can unfreeze some layers of the base model and fine-tune the entire model with a lower learning rate.
"""

# Unfreeze the base model
base_model.trainable = True

# It's important to recompile the model after changing the `trainable` status of layers.
# Use a lower learning rate for fine-tuning to avoid destroying the pre-trained weights.
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5), # Very low learning rate
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

print("Starting fine-tuning...")
fine_tune_epochs = 10 # Additional epochs for fine-tuning
early_stop_fine_tune = EarlyStopping(patience=5, restore_best_weights=True, monitor='val_loss')

history_fine_tune = model.fit(
    train_data,
    validation_data=val_data,
    epochs=fine_tune_epochs,
    callbacks=[early_stop_fine_tune]
)
print("Fine-tuning complete.")

"""### Visualization After Fine-tuning

Let's plot the accuracy and loss again to see the impact of fine-tuning.
"""

plt.figure(figsize=(12, 5))

# Plot training & validation accuracy values after fine-tuning
plt.subplot(1, 2, 1)
plt.plot(history_fine_tune.history['accuracy'])
plt.plot(history_fine_tune.history['val_accuracy'])
plt.title('Fine-tuned Model accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'], loc='upper left')

# Plot training & validation loss values after fine-tuning
plt.subplot(1, 2, 2)
plt.plot(history_fine_tune.history['loss'])
plt.plot(history_fine_tune.history['val_loss'])
plt.title('Fine-tuned Model loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'], loc='upper left')

plt.tight_layout()
plt.show()

model.save("breed_model.h5")

"""## 10. Real-time Image Prediction

Upload an image from your local machine to get a prediction from the trained model. This uses the `predict_image` function defined earlier.
"""

print("Please upload an image for prediction:")
uploaded = files.upload()

for fn in uploaded.keys():
    print('User uploaded file "{name}" with length {length} bytes'.format(
        name=fn, length=len(uploaded[fn])))

    # Save the uploaded file temporarily
    with open(fn, 'wb') as f:
        f.write(uploaded[fn])

    # Display the uploaded image
    print("\nUploaded Image:")
    display(Image(filename=fn, width=200))

    # Make prediction
    try:
        prediction_results = predict_image(fn)
        print("\nPrediction Results:")
        print(f"Primary Breed: {prediction_results['primary_breed']} (Confidence: {prediction_results['confidence']:.2f})")
        print(f"Secondary Breed: {prediction_results['secondary_breed']}")
        print(f"Crossbreed Ratio (all classes): {prediction_results['crossbreed_ratio']}")
    except FileNotFoundError as e:
        print(e)
    except Exception as e:
        print(f"An error occurred during prediction: {e}")

    # Clean up the uploaded file
    os.remove(fn)
    print(f"Cleaned up temporary file: {fn}")