"""
Husbandry reference for the breeds the classifier can predict.

Keys match the model's class names (`Cattle_Gir`, `Buffalo_Murrah`, ...) as
produced by ml-service/scripts/prepare_dataset.py. Lookup is tolerant: it
accepts the prefixed name, the bare breed name, spaces or underscores, and any
casing, so older records that stored plain "Gir" still resolve.

Figures are typical ranges for the breed under normal Indian farm management
(NBAGR breed descriptors and state livestock department guidance). Yield in
particular varies widely with feed, parity and management - treat these as
indicative, not as a guarantee for an individual animal.
"""

from __future__ import annotations

# ── Cattle (Bos indicus) ────────────────────────────────────────────────────

_CATTLE: dict[str, dict] = {
    "Gir": {
        "milk_yield": "10-15 litres/day",
        "climate": "Hot, semi-arid",
        "origin": "Saurashtra, Gujarat",
        "feed": "Green fodder, dry roughage, cottonseed cake",
        "disease_risks": ["FMD", "Mastitis", "Brucellosis"],
        "best_for": "Heat-tolerant milk production; widely used for crossbreeding",
        "avg_weight_kg": 385,
        "lactation_days": 300,
    },
    "Red_Sindhi": {
        "milk_yield": "6-10 litres/day",
        "climate": "Very hot and dry",
        "origin": "Sindh region; now across India",
        "feed": "Dry fodder with minimal concentrate",
        "disease_risks": ["Tick fever", "Theileriosis", "FMD"],
        "best_for": "Hardy dairy breed for harsh, low-input conditions",
        "avg_weight_kg": 340,
        "lactation_days": 270,
    },
    "Sahiwal": {
        "milk_yield": "8-12 litres/day",
        "climate": "Hot and humid",
        "origin": "Punjab region",
        "feed": "Wheat straw, green fodder, mustard cake",
        "disease_risks": ["Tick fever", "FMD", "Mastitis"],
        "best_for": "Best indigenous dairy breed; strong heat tolerance",
        "avg_weight_kg": 450,
        "lactation_days": 280,
    },
    "Rathi": {
        "milk_yield": "6-8 litres/day",
        "climate": "Arid desert",
        "origin": "Rajasthan",
        "feed": "Desert grasses, guar, dry roughage",
        "disease_risks": ["Tick fever", "FMD"],
        "best_for": "Dairy in arid zones with scarce fodder",
        "avg_weight_kg": 320,
        "lactation_days": 280,
    },
    "Tharparkar": {
        "milk_yield": "7-10 litres/day",
        "climate": "Arid, drought-prone",
        "origin": "Thar desert, Rajasthan",
        "feed": "Sparse grazing, dry fodder",
        "disease_risks": ["FMD", "Tick fever"],
        "best_for": "Dual purpose; exceptional drought tolerance",
        "avg_weight_kg": 400,
        "lactation_days": 290,
    },
    "Kankrej": {
        "milk_yield": "5-8 litres/day",
        "climate": "Hot, semi-arid",
        "origin": "Kutch, Gujarat / Rajasthan",
        "feed": "Green fodder, dry roughage, grazing",
        "disease_risks": ["FMD", "HS", "Tick fever"],
        "best_for": "Dual purpose; powerful draught animal with a fast gait",
        "avg_weight_kg": 480,
        "lactation_days": 290,
    },
    "Hariana": {
        "milk_yield": "4-7 litres/day",
        "climate": "Hot, semi-arid plains",
        "origin": "Haryana",
        "feed": "Wheat straw, green fodder, concentrate",
        "disease_risks": ["FMD", "Mastitis", "HS"],
        "best_for": "Dual purpose; draught work and household milk",
        "avg_weight_kg": 430,
        "lactation_days": 270,
    },
    "Hansi": {
        "milk_yield": "4-6 litres/day",
        "climate": "Hot, semi-arid plains",
        "origin": "Hansi, Hisar district, Haryana",
        "feed": "Wheat straw, green fodder, concentrate",
        "disease_risks": ["FMD", "Mastitis", "HS"],
        "best_for": "Local Hariana-type strain; dual purpose farm cattle",
        "avg_weight_kg": 420,
        "lactation_days": 265,
    },
    "Hissar": {
        "milk_yield": "4-6 litres/day",
        "climate": "Hot, semi-arid plains",
        "origin": "Hisar, Haryana",
        "feed": "Wheat straw, green fodder, concentrate",
        "disease_risks": ["FMD", "Mastitis", "HS"],
        "best_for": "Hariana-type strain selected around the Hisar farm herds",
        "avg_weight_kg": 430,
        "lactation_days": 270,
    },
    "Ongole": {
        "milk_yield": "4-6 litres/day",
        "climate": "Hot, humid coastal",
        "origin": "Prakasam district, Andhra Pradesh",
        "feed": "Paddy straw, green fodder, grazing",
        "disease_risks": ["FMD", "HS", "Black quarter"],
        "best_for": "Heavy draught and beef-type frame; heat and tick resistant",
        "avg_weight_kg": 500,
        "lactation_days": 280,
    },
    "Krishna_Valley": {
        "milk_yield": "3-5 litres/day",
        "climate": "Hot, semi-arid black-soil tracts",
        "origin": "Krishna river valley, Karnataka",
        "feed": "Sorghum stover, green fodder",
        "disease_risks": ["FMD", "HS"],
        "best_for": "Heavy draught in deep black-cotton soil",
        "avg_weight_kg": 500,
        "lactation_days": 260,
    },
    "Deoni": {
        "milk_yield": "4-6 litres/day",
        "climate": "Semi-arid Deccan plateau",
        "origin": "Latur, Maharashtra",
        "feed": "Sorghum stover, green fodder, concentrate",
        "disease_risks": ["FMD", "Mastitis"],
        "best_for": "Dual purpose; steady milk with good draught ability",
        "avg_weight_kg": 410,
        "lactation_days": 280,
    },
    "Khillari": {
        "milk_yield": "2-4 litres/day",
        "climate": "Hot, dry Deccan",
        "origin": "Maharashtra / North Karnataka",
        "feed": "Dry roughage, grazing",
        "disease_risks": ["FMD", "HS"],
        "best_for": "Fast, powerful draught; low milk output",
        "avg_weight_kg": 450,
        "lactation_days": 240,
    },
    "Hallikar": {
        "milk_yield": "2-4 litres/day",
        "climate": "Dry southern plateau",
        "origin": "Tumkur / Mysore, Karnataka",
        "feed": "Grazing, ragi straw, dry fodder",
        "disease_risks": ["FMD", "HS"],
        "best_for": "Premier draught breed; foundation of Amrit Mahal",
        "avg_weight_kg": 340,
        "lactation_days": 240,
    },
    "Amritmahal": {
        "milk_yield": "1-3 litres/day",
        "climate": "Dry southern plateau",
        "origin": "Karnataka",
        "feed": "Extensive grazing, dry fodder",
        "disease_risks": ["FMD", "HS"],
        "best_for": "Fast draught and cart work; very hardy",
        "avg_weight_kg": 350,
        "lactation_days": 210,
    },
    "Kangayam": {
        "milk_yield": "3-5 litres/day",
        "climate": "Hot, dry",
        "origin": "Kongu region, Tamil Nadu",
        "feed": "Kolukattai grass, dry fodder, grazing",
        "disease_risks": ["FMD", "HS"],
        "best_for": "Strong draught; well suited to dry-land farming",
        "avg_weight_kg": 400,
        "lactation_days": 250,
    },
    "Pulikulam": {
        "milk_yield": "1-2 litres/day",
        "climate": "Hot, dry",
        "origin": "Madurai / Sivaganga, Tamil Nadu",
        "feed": "Free grazing on common land",
        "disease_risks": ["FMD", "HS"],
        "best_for": "Draught and traditional jallikattu stock; reared in herds",
        "avg_weight_kg": 300,
        "lactation_days": 200,
    },
    "Umblachery": {
        "milk_yield": "2-4 litres/day",
        "climate": "Humid coastal delta",
        "origin": "Nagapattinam, Tamil Nadu",
        "feed": "Paddy straw, green fodder",
        "disease_risks": ["FMD", "HS", "Foot rot"],
        "best_for": "Wet-land ploughing in marshy paddy fields",
        "avg_weight_kg": 300,
        "lactation_days": 230,
    },
    "Bargur": {
        "milk_yield": "2-3 litres/day",
        "climate": "Hilly forest tracts",
        "origin": "Bargur hills, Erode, Tamil Nadu",
        "feed": "Forest grazing, dry fodder",
        "disease_risks": ["FMD", "HS"],
        "best_for": "Agile draught on hilly terrain; known for speed",
        "avg_weight_kg": 300,
        "lactation_days": 210,
    },
    "Vechur": {
        "milk_yield": "2-3 litres/day",
        "climate": "Hot, humid tropical",
        "origin": "Kottayam, Kerala",
        "feed": "Green fodder, kitchen residues, grazing",
        "disease_risks": ["FMD", "Mastitis"],
        "best_for": "Smallest cattle breed in the world; very low feed needs",
        "avg_weight_kg": 130,
        "lactation_days": 240,
    },
    "Kasargod": {
        "milk_yield": "1-3 litres/day",
        "climate": "Humid coastal",
        "origin": "Kasaragod, Kerala",
        "feed": "Grazing, green fodder, agricultural residues",
        "disease_risks": ["FMD", "Tick fever"],
        "best_for": "Dwarf backyard cattle; disease-resistant and low input",
        "avg_weight_kg": 150,
        "lactation_days": 220,
    },
    "Malnad_Gidda": {
        "milk_yield": "1-3 litres/day",
        "climate": "Heavy rainfall, hilly",
        "origin": "Western Ghats, Karnataka",
        "feed": "Forest grazing, green fodder",
        "disease_risks": ["FMD", "Foot rot", "Tick fever"],
        "best_for": "Dwarf hill breed; thrives in high-rainfall forest country",
        "avg_weight_kg": 120,
        "lactation_days": 220,
    },
    "Nagori": {
        "milk_yield": "2-4 litres/day",
        "climate": "Arid",
        "origin": "Nagaur, Rajasthan",
        "feed": "Dry fodder, guar, grazing",
        "disease_risks": ["FMD", "HS"],
        "best_for": "Fast trotting draught bullocks",
        "avg_weight_kg": 400,
        "lactation_days": 230,
    },
    "Nimari": {
        "milk_yield": "3-5 litres/day",
        "climate": "Hot, semi-arid",
        "origin": "Nimar, Madhya Pradesh",
        "feed": "Sorghum stover, green fodder",
        "disease_risks": ["FMD", "HS"],
        "best_for": "Dual purpose; sturdy draught with moderate milk",
        "avg_weight_kg": 400,
        "lactation_days": 260,
    },
    "Dangi": {
        "milk_yield": "3-5 litres/day",
        "climate": "Heavy rainfall, hilly",
        "origin": "Ahmednagar / Nashik, Maharashtra",
        "feed": "Grazing, green fodder, dry roughage",
        "disease_risks": ["FMD", "Foot rot"],
        "best_for": "Draught in heavy-rainfall hill country; oily coat sheds water",
        "avg_weight_kg": 350,
        "lactation_days": 250,
    },
    "Kenkatha": {
        "milk_yield": "2-4 litres/day",
        "climate": "Hot, semi-arid",
        "origin": "Bundelkhand, UP / MP",
        "feed": "Dry fodder, grazing on scrub",
        "disease_risks": ["FMD", "HS"],
        "best_for": "Small hardy draught for rocky Bundelkhand terrain",
        "avg_weight_kg": 280,
        "lactation_days": 220,
    },
    "Kenwariya": {
        "milk_yield": "2-3 litres/day",
        "climate": "Hot, semi-arid",
        "origin": "Bundelkhand, Madhya Pradesh",
        "feed": "Scrub grazing, dry fodder",
        "disease_risks": ["FMD", "HS"],
        "best_for": "Compact grey draught cattle; close kin of the Kenkatha",
        "avg_weight_kg": 290,
        "lactation_days": 210,
    },
    "Kherigarh": {
        "milk_yield": "2-3 litres/day",
        "climate": "Sub-humid plains",
        "origin": "Kheri, Uttar Pradesh",
        "feed": "Grazing, paddy and wheat straw",
        "disease_risks": ["FMD", "HS"],
        "best_for": "Active light draught; largely grazed on forest margins",
        "avg_weight_kg": 300,
        "lactation_days": 210,
    },
    "Alambadi": {
        "milk_yield": "1-2 litres/day",
        "climate": "Dry hilly forest",
        "origin": "Dharmapuri, Tamil Nadu",
        "feed": "Forest grazing, dry fodder",
        "disease_risks": ["FMD", "HS"],
        "best_for": "Hardy draught; a threatened breed with small numbers left",
        "avg_weight_kg": 300,
        "lactation_days": 200,
    },
    "Poda_Thirupu": {
        "milk_yield": "3-5 litres/day",
        "climate": "Hot, semi-arid",
        "origin": "Nalgonda / Suryapet, Telangana",
        "feed": "Grazing, paddy straw, concentrate",
        "disease_risks": ["FMD", "HS"],
        "best_for": "Dual purpose; distinctive white-spotted red coat",
        "avg_weight_kg": 340,
        "lactation_days": 230,
    },
    "Bhelahi": {
        "milk_yield": "2-4 litres/day",
        "climate": "Hot, sub-humid",
        "origin": "Bhelahi tract, Chhattisgarh",
        "feed": "Scrub grazing, paddy straw",
        "disease_risks": ["FMD", "HS", "Parasites"],
        "best_for": "Hardy small draught cattle for smallholders",
        "avg_weight_kg": 280,
        "lactation_days": 200,
    },
    "Ghumusari": {
        "milk_yield": "2-3 litres/day",
        "climate": "Hot, humid coastal",
        "origin": "Ganjam, Odisha",
        "feed": "Grazing, paddy straw",
        "disease_risks": ["FMD", "HS", "Parasites"],
        "best_for": "Compact white draught cattle of coastal Odisha",
        "avg_weight_kg": 270,
        "lactation_days": 200,
    },
    "Ayrshire": {
        "milk_yield": "18-25 litres/day",
        "climate": "Temperate; needs shade and cooling in Indian summers",
        "origin": "Ayrshire, Scotland",
        "feed": "High-energy ration, green fodder, mineral mix",
        "disease_risks": ["Mastitis", "Milk fever", "Heat stress"],
        "best_for": "Exotic dairy breed; used in crossbreeding, not heat hardy",
        "avg_weight_kg": 550,
        "lactation_days": 305,
    },
    "Gangatiri": {
        "milk_yield": "4-6 litres/day",
        "climate": "Sub-humid Gangetic plains",
        "origin": "Eastern UP / Bihar",
        "feed": "Paddy straw, green fodder, concentrate",
        "disease_risks": ["FMD", "Mastitis", "HS"],
        "best_for": "Dual purpose along the Ganga belt",
        "avg_weight_kg": 350,
        "lactation_days": 260,
    },
    "Gaolao": {
        "milk_yield": "3-5 litres/day",
        "climate": "Hot, dry",
        "origin": "Wardha, Maharashtra / MP border",
        "feed": "Sorghum stover, grazing",
        "disease_risks": ["FMD", "HS"],
        "best_for": "Fast light draught for road and field work",
        "avg_weight_kg": 340,
        "lactation_days": 240,
    },
    "Mewati": {
        "milk_yield": "4-6 litres/day",
        "climate": "Semi-arid",
        "origin": "Mewat, Haryana / Rajasthan",
        "feed": "Green fodder, dry roughage, concentrate",
        "disease_risks": ["FMD", "Mastitis"],
        "best_for": "Dual purpose; docile and good for heavy ploughing",
        "avg_weight_kg": 420,
        "lactation_days": 270,
    },
    "Red_Kandhari": {
        "milk_yield": "3-5 litres/day",
        "climate": "Semi-arid Deccan",
        "origin": "Nanded, Maharashtra",
        "feed": "Sorghum stover, grazing",
        "disease_risks": ["FMD", "HS"],
        "best_for": "Sturdy draught; uniform deep-red coat",
        "avg_weight_kg": 400,
        "lactation_days": 250,
    },
    "Punganur": {
        "milk_yield": "1-3 litres/day",
        "climate": "Hot, dry",
        "origin": "Chittoor, Andhra Pradesh",
        "feed": "Minimal - very efficient converter of dry fodder",
        "disease_risks": ["FMD", "Mastitis"],
        "best_for": "One of the smallest dairy breeds; extremely low feed needs",
        "avg_weight_kg": 130,
        "lactation_days": 220,
    },
    "Badri": {
        "milk_yield": "1-3 litres/day",
        "climate": "Cold mountain",
        "origin": "Uttarakhand hills",
        "feed": "Hill grazing, green fodder",
        "disease_risks": ["FMD", "Foot rot"],
        "best_for": "Small hill cattle; milk noted for high fat",
        "avg_weight_kg": 150,
        "lactation_days": 220,
    },
    "Siri": {
        "milk_yield": "2-4 litres/day",
        "climate": "Cold Himalayan",
        "origin": "Sikkim / Darjeeling hills",
        "feed": "Hill grazing, fodder trees",
        "disease_risks": ["FMD", "Foot rot"],
        "best_for": "Draught and milk in steep mountain terrain",
        "avg_weight_kg": 300,
        "lactation_days": 230,
    },
    "Ladakhi": {
        "milk_yield": "1-2 litres/day",
        "climate": "Cold high-altitude desert",
        "origin": "Ladakh",
        "feed": "Alfalfa, barley straw, limited grazing",
        "disease_risks": ["FMD", "Respiratory infections"],
        "best_for": "Survives extreme cold and thin air above 3000 m",
        "avg_weight_kg": 200,
        "lactation_days": 200,
    },
    "Lakhimi": {
        "milk_yield": "1-3 litres/day",
        "climate": "Hot, very humid",
        "origin": "Assam",
        "feed": "Grazing, paddy straw",
        "disease_risks": ["FMD", "HS", "Parasites"],
        "best_for": "Small hardy cattle for the humid Brahmaputra valley",
        "avg_weight_kg": 160,
        "lactation_days": 210,
    },
    "Bachaur": {
        "milk_yield": "2-4 litres/day",
        "climate": "Sub-humid plains",
        "origin": "Sitamarhi, Bihar",
        "feed": "Paddy straw, grazing",
        "disease_risks": ["FMD", "HS"],
        "best_for": "Draught in the north Bihar plains",
        "avg_weight_kg": 320,
        "lactation_days": 220,
    },
    "Belahi": {
        "milk_yield": "3-5 litres/day",
        "climate": "Semi-arid foothills",
        "origin": "Haryana / Chandigarh Shivalik foothills",
        "feed": "Grazing, green fodder, straw",
        "disease_risks": ["FMD", "Tick fever"],
        "best_for": "Dual purpose; migratory herds in the Shivalik belt",
        "avg_weight_kg": 320,
        "lactation_days": 240,
    },
    "Binjharpuri": {
        "milk_yield": "2-4 litres/day",
        "climate": "Hot, humid coastal",
        "origin": "Jajpur, Odisha",
        "feed": "Paddy straw, grazing",
        "disease_risks": ["FMD", "HS"],
        "best_for": "Draught and household milk in coastal Odisha",
        "avg_weight_kg": 300,
        "lactation_days": 230,
    },
    "Ghumusari": {
        "milk_yield": "1-3 litres/day",
        "climate": "Hot, humid",
        "origin": "Ganjam, Odisha",
        "feed": "Grazing, paddy straw",
        "disease_risks": ["FMD", "HS"],
        "best_for": "Small hardy draught cattle; white coat, compact frame",
        "avg_weight_kg": 250,
        "lactation_days": 210,
    },
    "Kosali": {
        "milk_yield": "1-3 litres/day",
        "climate": "Hot, sub-humid",
        "origin": "Chhattisgarh plains",
        "feed": "Paddy straw, grazing",
        "disease_risks": ["FMD", "HS"],
        "best_for": "Small draught cattle for smallholder paddy farms",
        "avg_weight_kg": 220,
        "lactation_days": 210,
    },
    "Malvi": {
        "milk_yield": "2-4 litres/day",
        "climate": "Semi-arid plateau",
        "origin": "Malwa, Madhya Pradesh",
        "feed": "Sorghum stover, grazing",
        "disease_risks": ["FMD", "HS"],
        "best_for": "Sturdy grey draught cattle for the Malwa plateau",
        "avg_weight_kg": 400,
        "lactation_days": 230,
    },
    "Motu": {
        "milk_yield": "1-2 litres/day",
        "climate": "Hot, humid tribal uplands",
        "origin": "Koraput, Odisha / AP border",
        "feed": "Free grazing, crop residues",
        "disease_risks": ["FMD", "HS", "Parasites"],
        "best_for": "Very hardy small draught cattle in tribal areas",
        "avg_weight_kg": 220,
        "lactation_days": 200,
    },
    "Ponwar": {
        "milk_yield": "1-3 litres/day",
        "climate": "Sub-humid terai",
        "origin": "Pilibhit, Uttar Pradesh",
        "feed": "Grazing, paddy straw",
        "disease_risks": ["FMD", "HS"],
        "best_for": "Agile light draught; alert temperament",
        "avg_weight_kg": 280,
        "lactation_days": 200,
    },
    "Purnea": {
        "milk_yield": "2-4 litres/day",
        "climate": "Humid Gangetic plains",
        "origin": "Purnea, Bihar",
        "feed": "Paddy straw, green fodder",
        "disease_risks": ["FMD", "HS"],
        "best_for": "Dual purpose smallholder cattle in east Bihar",
        "avg_weight_kg": 280,
        "lactation_days": 220,
    },
    "Poda_Thurpu": {
        "milk_yield": "2-3 litres/day",
        "climate": "Hot, dry",
        "origin": "Nalgonda, Telangana",
        "feed": "Grazing, sorghum stover",
        "disease_risks": ["FMD", "HS"],
        "best_for": "Draught cattle with distinctive white-spotted face",
        "avg_weight_kg": 280,
        "lactation_days": 210,
    },
    "Konkan_Kapila": {
        "milk_yield": "1-3 litres/day",
        "climate": "Heavy rainfall coastal",
        "origin": "Konkan coast, Maharashtra",
        "feed": "Grazing, green fodder",
        "disease_risks": ["FMD", "Foot rot"],
        "best_for": "Small hardy cattle for high-rainfall coastal strips",
        "avg_weight_kg": 200,
        "lactation_days": 210,
    },
    "Himachali_Pahari": {
        "milk_yield": "2-3 litres/day",
        "climate": "Cold mountain",
        "origin": "Himachal Pradesh",
        "feed": "Hill grazing, fodder trees, straw",
        "disease_risks": ["FMD", "Foot rot"],
        "best_for": "Small hill cattle for steep terrain and cold winters",
        "avg_weight_kg": 180,
        "lactation_days": 220,
    },
    "Dagri": {
        "milk_yield": "2-3 litres/day",
        "climate": "Semi-arid",
        "origin": "Dahod, Gujarat",
        "feed": "Grazing, maize stover",
        "disease_risks": ["FMD", "HS"],
        "best_for": "Light, agile draught cattle for tribal Gujarat",
        "avg_weight_kg": 300,
        "lactation_days": 220,
    },
    "Khariar": {
        "milk_yield": "1-3 litres/day",
        "climate": "Hot, sub-humid",
        "origin": "Nuapada, Odisha",
        "feed": "Grazing, paddy straw",
        "disease_risks": ["FMD", "HS"],
        "best_for": "Compact draught cattle for western Odisha",
        "avg_weight_kg": 240,
        "lactation_days": 210,
    },
    "Nari": {
        "milk_yield": "3-5 litres/day",
        "climate": "Arid",
        "origin": "Sirohi / Pali, Rajasthan",
        "feed": "Desert grazing, dry fodder",
        "disease_risks": ["FMD", "Tick fever"],
        "best_for": "Dual purpose desert cattle",
        "avg_weight_kg": 320,
        "lactation_days": 240,
    },
    "Shweta_Kapila": {
        "milk_yield": "1-3 litres/day",
        "climate": "Humid coastal",
        "origin": "Goa",
        "feed": "Grazing, green fodder",
        "disease_risks": ["FMD", "Foot rot"],
        "best_for": "Small white coastal cattle; low input needs",
        "avg_weight_kg": 200,
        "lactation_days": 210,
    },
    "Thutho": {
        "milk_yield": "1-2 litres/day",
        "climate": "Cold humid hills",
        "origin": "Nagaland",
        "feed": "Forest grazing, crop residues",
        "disease_risks": ["FMD", "Parasites"],
        "best_for": "Hardy hill cattle kept by smallholders in the north-east",
        "avg_weight_kg": 200,
        "lactation_days": 200,
    },
    "Frieswal": {
        "milk_yield": "15-20 litres/day",
        "climate": "Temperate to sub-tropical",
        "origin": "Crossbred (Holstein Friesian x Sahiwal), developed in India",
        "feed": "Balanced concentrate, green fodder, silage",
        "disease_risks": ["Mastitis", "Milk fever", "FMD"],
        "best_for": "High-yield crossbred dairy with partial heat tolerance",
        "avg_weight_kg": 470,
        "lactation_days": 300,
    },
    "Karan_Swiss": {
        "milk_yield": "14-18 litres/day",
        "climate": "Temperate to sub-tropical",
        "origin": "Crossbred (Brown Swiss x Sahiwal/Red Sindhi), NDRI Karnal",
        "feed": "Concentrate, green fodder, silage",
        "disease_risks": ["Mastitis", "Milk fever"],
        "best_for": "Crossbred dairy with good persistency",
        "avg_weight_kg": 450,
        "lactation_days": 300,
    },
    # ── Exotic dairy breeds (kept for older records) ────────────────────────
    "Holstein": {
        "milk_yield": "25-35 litres/day",
        "climate": "Temperate, cooler regions",
        "origin": "Netherlands / Germany",
        "feed": "High-energy concentrate, maize silage",
        "disease_risks": ["Mastitis", "Milk fever", "Ketosis"],
        "best_for": "Maximum milk volume where cooling is available",
        "avg_weight_kg": 680,
        "lactation_days": 305,
    },
    "Jersey": {
        "milk_yield": "12-20 litres/day",
        "climate": "Temperate to warm",
        "origin": "Jersey, Channel Islands",
        "feed": "Balanced concentrate with green fodder",
        "disease_risks": ["Milk fever", "Bloat", "Mastitis"],
        "best_for": "High-fat milk; smaller frame than Holstein",
        "avg_weight_kg": 410,
        "lactation_days": 300,
    },
}

# ── Buffalo (Bubalus bubalis) ───────────────────────────────────────────────

_BUFFALO: dict[str, dict] = {
    "Murrah": {
        "milk_yield": "15-25 litres/day",
        "climate": "Hot, semi-arid to humid",
        "origin": "Haryana / Punjab",
        "feed": "Green fodder, dry fodder, concentrate mix",
        "disease_risks": ["Mastitis", "HS", "Foot rot"],
        "best_for": "Highest-yielding buffalo breed; very high fat milk",
        "avg_weight_kg": 550,
        "lactation_days": 300,
    },
    "Nili_Ravi": {
        "milk_yield": "12-18 litres/day",
        "climate": "Hot, semi-arid",
        "origin": "Sutlej and Ravi valleys, Punjab",
        "feed": "Berseem, maize fodder, concentrate",
        "disease_risks": ["Mastitis", "HS"],
        "best_for": "High-yield dairy buffalo; wall-eyes and white markings",
        "avg_weight_kg": 550,
        "lactation_days": 300,
    },
    "Jaffarabadi": {
        "milk_yield": "10-16 litres/day",
        "climate": "Hot, semi-arid coastal",
        "origin": "Gir forest / Jafrabad, Gujarat",
        "feed": "Green fodder, dry roughage, concentrate",
        "disease_risks": ["Mastitis", "HS", "Foot rot"],
        "best_for": "Heaviest Indian buffalo; very rich milk",
        "avg_weight_kg": 700,
        "lactation_days": 290,
    },
    "Mehsana": {
        "milk_yield": "10-15 litres/day",
        "climate": "Hot, semi-arid",
        "origin": "Mehsana, Gujarat",
        "feed": "Green fodder, cottonseed cake, concentrate",
        "disease_risks": ["Mastitis", "HS"],
        "best_for": "Reliable dairy buffalo with a long lactation",
        "avg_weight_kg": 500,
        "lactation_days": 300,
    },
    "Surti": {
        "milk_yield": "8-12 litres/day",
        "climate": "Hot, humid",
        "origin": "Surat / Kheda, Gujarat",
        "feed": "Green fodder, dry fodder, concentrate",
        "disease_risks": ["Mastitis", "HS"],
        "best_for": "Very high fat content, often above 7%",
        "avg_weight_kg": 410,
        "lactation_days": 290,
    },
    "Banni": {
        "milk_yield": "10-14 litres/day",
        "climate": "Arid desert grassland",
        "origin": "Banni grasslands, Kutch, Gujarat",
        "feed": "Night grazing on saline grassland, minimal concentrate",
        "disease_risks": ["Mastitis", "HS", "Tick fever"],
        "best_for": "Dairy buffalo that thrives on desert grazing alone",
        "avg_weight_kg": 475,
        "lactation_days": 290,
    },
    "Bhadawari": {
        "milk_yield": "4-6 litres/day",
        "climate": "Hot, semi-arid ravines",
        "origin": "Chambal ravines, UP / MP",
        "feed": "Grazing on ravine scrub, crop residues",
        "disease_risks": ["HS", "Parasites"],
        "best_for": "Highest butterfat of any buffalo (often 8-13%); ghee making",
        "avg_weight_kg": 400,
        "lactation_days": 270,
    },
    "Nagpuri": {
        "milk_yield": "4-7 litres/day",
        "climate": "Hot, dry",
        "origin": "Vidarbha, Maharashtra",
        "feed": "Sorghum stover, grazing, concentrate",
        "disease_risks": ["HS", "Mastitis"],
        "best_for": "Dual purpose; long flat curved horns, good draught",
        "avg_weight_kg": 430,
        "lactation_days": 270,
    },
    "Toda": {
        "milk_yield": "2-4 litres/day",
        "climate": "Cool high-altitude grassland",
        "origin": "Nilgiri hills, Tamil Nadu",
        "feed": "Free grazing on shola grassland",
        "disease_risks": ["Parasites", "Foot rot"],
        "best_for": "Semi-wild breed central to Toda pastoral culture",
        "avg_weight_kg": 380,
        "lactation_days": 230,
    },
    "Pandharpuri": {
        "milk_yield": "6-9 litres/day",
        "climate": "Hot, dry",
        "origin": "Solapur, Maharashtra",
        "feed": "Sorghum stover, green fodder",
        "disease_risks": ["HS", "Mastitis"],
        "best_for": "Distinctive long sword-like horns; hardy dairy buffalo",
        "avg_weight_kg": 450,
        "lactation_days": 280,
    },
    "Chilika": {
        "milk_yield": "3-5 litres/day",
        "climate": "Humid brackish coastal",
        "origin": "Chilika lake, Odisha",
        "feed": "Saline marsh grazing, paddy straw",
        "disease_risks": ["Parasites", "HS", "Foot rot"],
        "best_for": "Tolerates brackish water and marshland grazing",
        "avg_weight_kg": 350,
        "lactation_days": 250,
    },
    "Marathwadi": {
        "milk_yield": "3-5 litres/day",
        "climate": "Semi-arid",
        "origin": "Marathwada, Maharashtra",
        "feed": "Sorghum stover, grazing",
        "disease_risks": ["HS", "Mastitis"],
        "best_for": "Dual purpose buffalo for dryland Marathwada",
        "avg_weight_kg": 400,
        "lactation_days": 260,
    },
    "Kalahandi": {
        "milk_yield": "2-4 litres/day",
        "climate": "Hot, sub-humid",
        "origin": "Kalahandi, Odisha",
        "feed": "Forest grazing, paddy straw",
        "disease_risks": ["HS", "Parasites"],
        "best_for": "Draught and modest milk in tribal Odisha",
        "avg_weight_kg": 380,
        "lactation_days": 240,
    },
    "Gojri": {
        "milk_yield": "5-7 litres/day",
        "climate": "Sub-tropical foothills",
        "origin": "Shivalik foothills, Punjab / HP",
        "feed": "Migratory grazing, green fodder",
        "disease_risks": ["HS", "Foot rot"],
        "best_for": "Buffalo of the migratory Gujjar herders",
        "avg_weight_kg": 420,
        "lactation_days": 260,
    },
    "Chhattisgarhi": {
        "milk_yield": "2-4 litres/day",
        "climate": "Hot, sub-humid",
        "origin": "Chhattisgarh",
        "feed": "Paddy straw, grazing",
        "disease_risks": ["HS", "Parasites"],
        "best_for": "Draught and household milk for smallholders",
        "avg_weight_kg": 350,
        "lactation_days": 240,
    },
    "Bargur": {
        "milk_yield": "2-4 litres/day",
        "climate": "Hilly forest",
        "origin": "Bargur hills, Tamil Nadu",
        "feed": "Forest grazing",
        "disease_risks": ["Parasites", "Foot rot"],
        "best_for": "Small hill buffalo reared in forest herds",
        "avg_weight_kg": 320,
        "lactation_days": 230,
    },
    "Luitswamp": {
        "milk_yield": "1-3 litres/day",
        "climate": "Hot, very humid",
        "origin": "Brahmaputra valley, Assam",
        "feed": "Marsh grazing, paddy straw",
        "disease_risks": ["Parasites", "HS", "Foot rot"],
        "best_for": "Swamp buffalo used for ploughing wet paddy",
        "avg_weight_kg": 350,
        "lactation_days": 220,
    },
    "Manda": {
        "milk_yield": "2-3 litres/day",
        "climate": "Hot upland",
        "origin": "Koraput, Odisha",
        "feed": "Hill grazing, crop residues",
        "disease_risks": ["Parasites", "HS"],
        "best_for": "Small draught buffalo of the Eastern Ghats",
        "avg_weight_kg": 300,
        "lactation_days": 220,
    },
    "Godavari": {
        "milk_yield": "4-6 litres/day",
        "climate": "Humid coastal delta",
        "origin": "Godavari delta, Andhra Pradesh",
        "feed": "Paddy straw, green fodder, concentrate",
        "disease_risks": ["Mastitis", "HS"],
        "best_for": "Delta dairy buffalo",
        "avg_weight_kg": 400,
        "lactation_days": 260,
    },
    "Sambalpuri": {
        "milk_yield": "2-4 litres/day",
        "climate": "Hot, sub-humid",
        "origin": "Sambalpur, Odisha",
        "feed": "Grazing, paddy straw",
        "disease_risks": ["HS", "Parasites"],
        "best_for": "Dual purpose buffalo for western Odisha",
        "avg_weight_kg": 360,
        "lactation_days": 240,
    },
    "South_Kanara": {
        "milk_yield": "2-3 litres/day",
        "climate": "Heavy rainfall coastal",
        "origin": "Dakshina Kannada, Karnataka",
        "feed": "Grazing, paddy straw",
        "disease_risks": ["Foot rot", "Parasites"],
        "best_for": "Coastal buffalo; also raced in traditional Kambala",
        "avg_weight_kg": 330,
        "lactation_days": 220,
    },
}


def _build_index() -> dict[str, dict]:
    index: dict[str, dict] = {}

    def register(key: str, payload: dict, species: str) -> None:
        entry = {**payload, "species": species}
        normalised = key.replace("_", " ").strip().lower()
        # Bare name, prefixed name, and space/underscore variants all resolve.
        for variant in {
            key.lower(),
            normalised,
            normalised.replace(" ", "_"),
            f"{species.lower()}_{normalised.replace(' ', '_')}",
            f"{species.lower()} {normalised}",
        }:
            index.setdefault(variant, entry)

    for name, payload in _CATTLE.items():
        register(name, payload, "Cattle")
    for name, payload in _BUFFALO.items():
        register(name, payload, "Buffalo")
    return index


_INDEX = _build_index()

# Kept for the chat service, which feeds the breed table to the model as context.
BREED_INFO = {**{f"Cattle_{k}": v for k, v in _CATTLE.items()},
              **{f"Buffalo_{k}": v for k, v in _BUFFALO.items()}}


# The dataset folders spell several breeds differently from the reference
# tables above. Without these, a class the model genuinely predicts would show
# no husbandry guidance at all.
_SPELLING_ALIASES = {
    "jaffrabadi": "jaffarabadi",
    "jafarabadi": "jaffarabadi",
    "jafrabadi": "jaffarabadi",
    "gangatri": "gangatiri",
    "gangatari": "gangatiri",
    "bhelai": "bhelahi",
    "ghumsari": "ghumusari",
    "poda_thirupu": "poda_thirupu",
    "luit": "luitswamp",
    "luit_swamp": "luitswamp",
    "ongole_dwarf": "ongole",
    "malnad_gidda": "malnad_gidda",
}


def get_breed_info(breed_name: str) -> dict:
    """
    Look up a breed's care information.

    Tolerates "Cattle_Gir", "Gir", "gir", "Red Sindhi" and "Red_Sindhi" alike,
    plus the alternate spellings the training folders use ("Jaffrabadi").
    Returns {} when the breed is not documented, so callers can degrade
    gracefully rather than showing placeholder facts.
    """
    if not breed_name:
        return {}

    candidate = str(breed_name).strip().lower()
    for key in (
        candidate,
        candidate.replace("_", " "),
        candidate.replace(" ", "_"),
    ):
        if key in _INDEX:
            return _INDEX[key]
        alias = _SPELLING_ALIASES.get(key.replace(" ", "_"))
        if alias and alias in _INDEX:
            return _INDEX[alias]

    # Strip a species prefix and retry ("cattle_gir" -> "gir").
    for prefix in ("cattle_", "buffalo_", "cattle ", "buffalo "):
        if candidate.startswith(prefix):
            return get_breed_info(candidate[len(prefix):])

    return {}
